version: '3.8'
services:
  db:
    image: mysql/mysql-server:latest
    container_name: CashFlow
    restart: always
    environment:
      - MYSQL_DATABASE=CashFlow
      - MYSQL_USER=CashFlow
      - MYSQL_PASSWORD=12345
      - MYSQL_ROOT_PASSWORD=12345
    ports:
      - '3306:3306'
